config/routes.rb
Rails.application.routes.draw do

  root to:"homes#top"
  devise_for :users
  get "/home/about" => "homes#about", as: "about"
  resources :books,only:[:new,:create,:index,:show,:edit,:update,:destroy]
  resources :users,only:[:index,:show,:edit,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title,presence:true
  validates :body,presence:true,length:{ maximum:200 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books,dependent: :destroy
  
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
   unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
   profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  validates :name,uniqueness:true,length:{ minimum:2, maximum:20 }
  validates :introduction,presence:false,length:{ maximum:50 }
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :correct_user, only: [:edit]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     flash[:notice] = 'You have created book successfully.'
     redirect_to book_path(@book.id)
    else
     render :index
    end
  end

  def show
    @books = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = 'You have updated book successfully.'
     redirect_to book_path(@book.id)
    else
     render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title,:body)
  end  
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end
  
  
  def show
    @user = User.find(params[:id])
    #@user = current_user.id
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:notice] = 'You have updated user successfully.'
     redirect_to user_path(@user.id)
    else
     render:edit
    end  
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path(current_user.id)) unless @user == current_user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id ="notice"></p>
  <div class ="container">
    <div class ="row">
      <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        
        <div id ="error_explanation">
         <% if @book.errors.any? %>
          <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
          <ul>
           <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
           <% end %>
          </ul>
         <% end %>
        </div>
        
        <%= form_with model:@book do |f| %>
          <div class ="form-group">
            <label for ="book_title">Title</label>
            <%= f.text_field :title,id:"book_title",class:"form-control book_title" %>
          </div>
          <div class ="form-group">
            <label for ="book_opinion">Opinion</label>
            <%= f.text_field :body,id:"book_body",class:"form-control book_body" %>
          </div>
          <div class ="form-group">
            <%= f.submit "Update Book",class:"btn btn-success" %>
          </div>
        <% end %>
        <%= link_to "Show",book_path(@book) %>
        /
        <%= link_to "Back",books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id ="notice"></p>
  <div class ="container px-5 px-sm-0">
    
    <div id ="error_explanation">
      <% if @book.errors.any? %>
       <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
       <ul>
        <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
       </ul>
      <% end %>
    </div>
    
    <div class ="row">
      <div class ="col-md-3">
        <h2>User info</h2>
        <%= image_tag current_user.get_profile_image(100,100) %>
        <table class ="table">
          <tbody>
             <tr></tr>
             <tr>
               <th>name</th>
               <th><%= current_user.name %></th>
             </tr>
             <tr>
               <th>introduction</th>
               <th><%= current_user.introduction %></th>
             </tr>
          </tbody>
        </table>
        
        <div class="row">
         <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block edit_user_id" do %>
          <i class="fas fa-user-cog"></i>
         <% end %>
        </div>
        
        <h2 class ="mt-3">New book</h2>
        <%= form_with model:@book do |f| %>
         <div class ="form-group">
          <label for ="book_title">Title</label>
          <%= f.text_field:title,class: "form-control book_title" %>    
         </div>
         <div class ="form-group">
          <label for ="book_opinion">Opinion</label>
          <%= f.text_area:body,class: "form-control book_body" %>     
         </div>
         <div class ="form-group">
          <%= f.submit 'Create Book',class: "btn btn-success" %>
         </div>
	    <% end %>
      </div>
      
      <div class ="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
             <tr>
               <td>
                <%= link_to user_path(book.user.id) do %> 
                  <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %>
               </td>
               <td>
                 <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                 <% end %>  
               </td>
               <td><%= book.body %></td>
             </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>


</main>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<main>
  <p id ="notice"></p>
  <div class ="container">
    <div class ="row">
      <div class ="col-md-3">
        <%= render 'users/info',user:@user,book:@books %>
      </div>
      <div class ="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class ="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                 <%= image_tag @book.user.get_profile_image(100,100) %>
                 <br><%= @user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <td>
                <% if @book.user == current_user %>
                 <%= link_to "Edit",edit_book_path(@book),class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
              <td>
                <% if @book.user == current_user %>
                 <%= link_to "Destroy",book_path(@book),class: "btn btn-sm btn-danger",method: :delete %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
    <p id="notice"></p>
    <div class="container">
        <div class="row">
            <h1 class="px-3 mx-auto">
                Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
            </h1>
        </div>
    </div>
</main>

app/views/homes/top.html.erb
<main>
 <p id="notice"></p>
 <div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
            <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
            <p>you can share and exchange your opinions , inpressions , and emotions</p>
            <p> about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                 <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
                </div>
                <div class="row">
                 <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
                </div>
            </div>
        </div>
    </div>
 </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
             <li>
              <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
               <i class="fas fa-home"></i>
               Home
              <% end %>
             </li>
             <li>
              <%= link_to users_path, class: "nav-link text-light" do %>
               <i class="fas fa-users"></i>
               Users
              <% end %>
             </li>
             <li>
              <%= link_to books_path, class: "nav-link text-light" do %>
               <i class="fas fa-book-open"></i>
               Books
              <% end %>
             </li>
             <li>
              <%= link_to destroy_user_session_path, class: "nav-link text-light", method: :delete do %>
               <i class="fas fa-sign-out-alt"></i>
               Log out
              <% end %>
             </li>
            <% else %>
             <li>
              <%= link_to root_path, class: "nav-link text-light" do %>
               <i class="fas fa-home"></i>
               Home
              <% end %>
             </li>
             <li>
              <%= link_to about_path, class: "nav-link text-light" do %>
               <i class="fas fa-link"></i>
               About
              <% end %>
             </li>
             <li>
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
               <i class="fas fa-user-plus"></i>
               Sign up
              <% end %> 
             </li>
             <li>
              <%= link_to new_user_session_path, class: "nav-link text-light" do %>
               <i class="fas fa-sign-in-alt"></i>
               Log in
              <% end %>
             </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <% if flash[:notice] %>
     <%= flash[:notice] %>
    <% end %>
    <% if flash[:alert] %>
     <%= flash[:alert] %>
    <% end %>
    
    <%= yield %>
    
    <footer>
     <div class="container mt-5">
      <div class="row">
       <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
       </div>
      </div>
     </div>
    </footer>
    
  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class ="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
        
  <div class="row">
    <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block edit_user_id" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
        
  <h2 class ="mt-3">New book</h2>
  <%= form_with model:book do |f| %>
    <div class ="form-group">
      <label for ="book_title">Title</label>
      <%= f.text_field:title,class: "form-control book_title" %>    
    </div>
    <div class ="form-group">
      <label for ="book_opinion">Opinion</label>
      <%= f.text_area:body,class: "form-control book_body" %>     
    </div>
    <div class ="form-group">
      <%= f.submit 'Create Book',class: "btn btn-success" %>
    </div>
	<% end %>

app/views/users/edit.html.erb
<main>
  <p id ="notice"></p>
  <div class="container">
    <div class ="row">
      <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        
        <div id ="error_explanation">
         <% if @user.errors.any? %>
          <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
          <ul>
           <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
           <% end %>
          </ul>
         <% end %>
        </div>
        
        <%= form_with model:@user do |f| %>
          <div class ="form-group">
            <label for ="user_name">Name</label>
            <%= f.text_field :name,id:"user_name",class:"form-control name" %>
          </div>
          <div class ="form-group">
            <label for ="user_image">Image</label>
            <%= f.file_field :profile_image,id:"user_profile_image",accept:"image/*",class:"form-control-file user_image" %>
          </div>
          <div class ="form-group">
            <label for ="user_introduction">Introduction</label>
            <%= f.text_field :introduction,id:"user_introduction",class:"form-control introduction" %>
          </div>
          <div class ="form-group">
            <%= f.submit "Update User",class:"btn btn-secondary" %>
          </div>
        <% end %>  
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id ="notice"></p>
  <div class ="container px-5 px-sm-0">
    <div class ="row">
      <div class ="col-md-3">
        <%= render 'info',user:@user,book:@book %>  
      </div>
      <div class ="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class ="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
           <% if user_signed_in? %>  
            <% @users.each do |user| %>
             <tr>
               <td>
                 <%= image_tag user.get_profile_image(80,80) %>
               </td>
               <td>
                 <%= user.name %>
               </td>
               <td>
                 <%= link_to "Show",user_path(user.id) %>
               </td>
             </tr>
            <% end %>
           <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id ="notice"></p>
  <div class ="container px-5 px-sm-0">
    <div class ="row">
      <div class ="col-md-3">
        <%= render 'info',user:@user,book:@book %>
      </div>
      <div class ="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class ="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
           <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                 <%= image_tag @user.get_profile_image(80,80) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
           <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>